### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by sbrugman** [szagoruyko/torch-caffe-binding#2]
When installing the Torch binding for Caffe (https://github.com/szagoruyko/torch-caffe-binding) I get the following error: tmp/luarocks_caffe-1.0-0-4572/torch-caffe-binding/caffe.cpp:5:27: fatal error: caffe/caffe.hpp: File or directory doesn't exists #include "caffe/caffe.hpp"

I've Caffe installed, in CPU only mode. Is this error related? Does anyone knows how to solve this? There is only very little documentation. Looks like I've missed something in the installation of Caffe.

**Comment by szagoruyko** [comment]
Are you sure you're installing the rock providing the full path to your caffe installation?
```CAFFE_DIR=/home/user/caffe luarocks install caffe```

**Comment by sbrugman** [comment]
This time I get the following error:
/tmp/luarocks_caffe-1.0-0-4007/torch-caffe-binding/caffe.cpp: In function ‘void init(void**, const char*, const char*)’:
/tmp/luarocks_caffe-1.0-0-4007/torch-caffe-binding/caffe.cpp:24:55: error: no matching function for call to ‘caffe::Net<float>::Net(std::string)’
   Net<float>* net_ = new Net<float>(string(param_file));

**Comment by szagoruyko** [comment]
caffe code is being changed without backward compatibility, let me check if it can be fixed fast

**Comment by szagoruyko** [comment]
ok it was easy, try to install again

**Comment by sbrugman** [comment]
Thank you
