### ISSUE TITLE
It seems that torch-caffe-binding can't process multi-input net

### ISSUE THREAD

**Issue by cloud-waiting-for-wind** [szagoruyko/torch-caffe-binding#7]
It seems that torch-caffe-binding can't process multi-input net

I have a caffe-net  with two input, I find it gets error when   
  output = net:forward(  {input_1, input_2}  ),

it seems that the torch-caffe-binding can only process one-input net

**Comment by szagoruyko** [comment]
no, it only supports one input networks, unfortunately.
